### ISSUE TITLE
Many links are rendered as text, not as links

### ISSUE THREAD

**Issue by bast** [orchid00/The_Carpentries_info#3]
I see that on https://orchid00.github.io/The_Carpentries_info/carpentries_style_shared_lessons.

I wanted to fix it but for this I wanted to see a preview on my computer (#2).

**Comment by orchid00** [comment]
Hi @bast 
Yes that's right. 
Initially I wanted links to be displayed, and because I wanted people to contribute on "easy" things I left it like that. My aim was people sending PRs to fix it, instead of me fixing all of those. Just need t add `[the_url](the_url)`

But, wait there.

when people click on any of those links, then it automatically redirects to another page, right. 

You'll be surprise of the number of people who seem "totally" confused about not being able to find the page they were looking at, just a second ago.
So I would probably go for adding some code to open link on a new tab. 
Does anyone what to work on that???

**Comment by bast** [comment]
It seems this should be possible with: `[name](url){:target="_blank"}`.

I fully agree with the strategy that others can send PRs to fix things. Also me opening issue does not mean that the owner should fix it. I only want to communicate that I know about the problem :-)

**Comment by orchid00** [comment]
this is now fixed with https://github.com/orchid00/The_Carpentries_info/commit/60aca2661579325c4552ec33eeedd508ce8c6ebc

**Comment by bast** [comment]
Thank you for the fix!
